apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argo
  name: workflow-role-binding
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io