apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: example
      eventSourceName: webhook-sensor
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-triggered-workflow-
                annotations:
                  workflows.argoproj.io/title: "demo"
                  workflows.argoproj.io/description: "{{inputs.parameters.description}}"
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:latest
                      command: ["/bin/sh", "-c"]
                      args: ["echo World"]
          parameters:
            - src:
                dependencyName: description
                dataKey: body.description
              dest: metadata.annotations.workflows\\.argoproj\\.io/description
            - src:
                dependencyName: title
                dataKey: body.title
              dest: metadata.annotations.workflows\\.argoproj\\.io/title