apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: example
      eventSourceName: webhook-sensor
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: "demo-sensor-workflow-"
                annotations:
                  "workflows.argoproj.io/description": "" # poprawione klucze w mapie
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:latest
                      command: ["/bin/sh", "-c"]
                      args: ["echo World"]
          parameters:
#            - src:
#                dependencyName: example
#                value: "`"
#              dest: metadata.annotations.workflows\.argoproj\.io\/description # Rozpoznanie pola description
#              operation: append
#            - src:
#                dependencyName: example
#                dataKey: body.description
#              dest: metadata.annotations.workflows\.argoproj\.io\/description # Rozpoznanie pola description
#              operation: append
#            - src:
#                dependencyName: example
#                value: "` "
#              dest: metadata.annotations.workflows\.argoproj\.io\/description # Rozpoznanie pola description
#              operation: append
#            - src:
#                dependencyName: example
#                dataKey: body.url
#              dest: metadata.annotations.workflows\.argoproj\.io\/description # Rozpoznanie pola description
#              operation: append
#            - src:
#                dependencyName: example
#                dataTemplate: "{{body.url}}"
#              dest: metadata.annotations.workflows\.argoproj\.io\/description # Rozpoznanie pola description
##              operation: append
            - src:
                dependencyName: example
                dataTemplate: "**{{ .Input.body.service }}** [{{.Input.body.mrName}}]({{.Input.body.mrUrl}})"
              dest: metadata.annotations.workflows\.argoproj\.io\/title
