apiVersion: v2
name: harbor
description: Harbor templates
type: application
version: 1.0.0

dependencies:
  - name: "harbor/harbor"
    version: "1.10.2"
    repository: https://helm.goharbor.io
